services:
  postgres:
    volumes:
      - psql_data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file: .env.postgres.prod
  pgadmin:
    env_file: .env.postgres.prod
  proclogic-api:
    image: proclogic-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file: .env.prod

volumes:
  psql_data:

# TODO: https://github.com/nginx-proxy/nginx-proxy
