services:
  # postgres:
  #   image: postgres
  #   container_name: postgres
  #   ports:
  #     - 5432:5432
  #   env_file: .env.postgres

  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8002:80"
    env_file: .env.postgres

  pgai:
    image: timescale/timescaledb-ha:pg17
    container_name: pgai
    environment:
      OPENAI_API_KEY: sk-svcacct-vqAzzSq-K-qsCbQVUBm-3d_mutvLbjtapLr4E95aiqGssh2C2I8yIe8xn6Mziz1O_AET3BlbkFJgfVcvb2qt02vnzwCvf2L3noSimUGjwNS0SBkgaHVEiW2YUz4we0r59elKFgRlXxElAA
    ports:
      - 5432:5432
    env_file: .env.postgres
