# TODO: https://www.beekeeperstudio.io/blog/docker-postgres
# TODO: https://docs.drone.io/server/provider/github/

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file: .env.postgres
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8002:80"
    env_file: .env.postgres
