"""init

Revision ID: 419516cab445
Revises: 
Create Date: 2025-06-05 00:17:32.228566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '419516cab445'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cpv_codes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('company_vat_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_vat_number'], ['companies.vat_number'], name=op.f('sectors_company_vat_number_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sectors_pkey'))
    )
    op.create_table('descriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('lot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dossier_reference_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cpv_code_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cpv_code_code'], ['cpv_codes.code'], name=op.f('descriptions_cpv_code_code_fkey')),
    sa.ForeignKeyConstraint(['dossier_reference_number'], ['dossiers.reference_number'], name=op.f('descriptions_dossier_reference_number_fkey')),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('descriptions_lot_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('descriptions_pkey'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('notification_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('company_vat_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('related_entity_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_vat_number'], ['companies.vat_number'], name=op.f('notifications_company_vat_number_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_table('publication_statuses',
    sa.Column('company_vat_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('publication_workspace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_vat_number'], ['companies.vat_number'], name=op.f('publication_statuses_company_vat_number_fkey')),
    sa.ForeignKeyConstraint(['publication_workspace_id'], ['publications.publication_workspace_id'], name=op.f('publication_statuses_publication_workspace_id_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['kanban_statuses.id'], name=op.f('publication_statuses_status_id_fkey')),
    sa.PrimaryKeyConstraint('company_vat_number', 'publication_workspace_id', name=op.f('publication_statuses_pkey'))
    )
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('citations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('messages_conversation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_table('dossiers',
    sa.Column('reference_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('accreditations', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('legal_basis', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('procurement_procedure_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('special_purchasing_technique', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('reference_number', name='dossiers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('companies',
    sa.Column('vat_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('emails', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('subscription', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number_of_employees', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('summary_activities', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('accreditations', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('max_publication_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activity_keywords', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('operating_regions', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('vat_number', name='companies_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_companies_emails'), 'companies', ['emails'], unique=False)
    op.create_table('publication_cpv_additional_codes',
    sa.Column('publication_publication_workspace_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cpv_code_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cpv_code_code'], ['cpv_codes.code'], name=op.f('publication_cpv_additional_codes_cpv_code_code_fkey')),
    sa.ForeignKeyConstraint(['publication_publication_workspace_id'], ['publications.publication_workspace_id'], name=op.f('publication_cpv_additional_co_publication_publication_work_fkey'))
    )
    op.create_table('publication_lots',
    sa.Column('publication_publication_workspace_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('publication_lots_lot_id_fkey')),
    sa.ForeignKeyConstraint(['publication_publication_workspace_id'], ['publications.publication_workspace_id'], name=op.f('publication_lots_publication_publication_workspace_id_fkey'))
    )
    op.create_table('company_publication_matches',
    sa.Column('company_vat_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('publication_workspace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('match_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_recommended', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_saved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_viewed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_vat_number'], ['companies.vat_number'], name=op.f('company_publication_matches_company_vat_number_fkey')),
    sa.ForeignKeyConstraint(['publication_workspace_id'], ['publications.publication_workspace_id'], name=op.f('company_publication_matches_publication_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('company_vat_number', 'publication_workspace_id', name=op.f('company_publication_matches_pkey'))
    )
    op.create_index(op.f('idx_match_recommended'), 'company_publication_matches', ['is_recommended'], unique=False)
    op.create_index(op.f('idx_match_publication'), 'company_publication_matches', ['publication_workspace_id'], unique=False)
    op.create_index(op.f('idx_match_percentage'), 'company_publication_matches', ['match_percentage'], unique=False)
    op.create_index(op.f('idx_match_company'), 'company_publication_matches', ['company_vat_number'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('publication_workspace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_vat_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('assistant_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_vat_number'], ['companies.vat_number'], name=op.f('conversations_company_vat_number_fkey')),
    sa.ForeignKeyConstraint(['publication_workspace_id'], ['publications.publication_workspace_id'], name=op.f('conversations_publication_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey'))
    )
    op.create_table('lots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reserved_execution', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('reserved_participation', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('lots_pkey'))
    )
    op.create_table('organisations',
    sa.Column('organisation_id', sa.INTEGER(), server_default=sa.text("nextval('organisations_organisation_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tree', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('organisation_id', name='organisations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('publications',
    sa.Column('publication_workspace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dispatch_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('insertion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('natures', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('notice_ids', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('notice_sub_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nuts_codes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('procedure_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('publication_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('publication_languages', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('publication_reference_numbers_bda', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('publication_reference_numbers_ted', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('publication_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.ARRAY(postgresql.TIMESTAMP()), autoincrement=False, nullable=False),
    sa.Column('reference_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.ARRAY(postgresql.TIMESTAMP()), autoincrement=False, nullable=False),
    sa.Column('ted_published', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('vault_submission_deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ai_summary_without_documents', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_summary_with_documents', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('award', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('estimated_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extracted_keywords', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('cpv_main_code_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dossier_reference_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cpv_main_code_code'], ['cpv_codes.code'], name=op.f('publications_cpv_main_code_code_fkey')),
    sa.ForeignKeyConstraint(['dossier_reference_number'], ['dossiers.reference_number'], name=op.f('publications_dossier_reference_number_fkey')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], name=op.f('publications_organisation_id_fkey')),
    sa.PrimaryKeyConstraint('publication_workspace_id', name=op.f('publications_pkey'))
    )
    op.create_index(op.f('ix_publications_vault_submission_deadline'), 'publications', ['vault_submission_deadline'], unique=False)
    op.create_index(op.f('ix_publications_nuts_codes'), 'publications', ['nuts_codes'], unique=False)
    op.create_table('organisation_names',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], name=op.f('organisation_names_organisation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('organisation_names_pkey')),
    sa.UniqueConstraint('text', 'language', name=op.f('_text_language_uc_org_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('enterprise_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('levels', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('dossier_reference_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dossier_reference_number'], ['dossiers.reference_number'], name=op.f('enterprise_categories_dossier_reference_number_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('enterprise_categories_pkey'))
    )
    op.create_table('cpv_codes',
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('cpv_codes_pkey'))
    )
    op.create_table('kanban_statuses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_vat_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_vat_number'], ['companies.vat_number'], name=op.f('kanban_statuses_company_vat_number_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kanban_statuses_pkey'))
    )
    # ### end Alembic commands ###
