"""init

Revision ID: 83ad5f3d264f
Revises: 
Create Date: 2025-02-08 23:30:17.756776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ad5f3d264f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('vat_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('summary_activities', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('vat_number')
    )
    op.create_table('cpv_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('dossiers',
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('accreditations', sa.PickleType(), nullable=True),
    sa.Column('legal_basis', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('procurement_procedure_type', sa.String(), nullable=True),
    sa.Column('special_purchasing_technique', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('reference_number')
    )
    op.create_table('lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reserved_execution', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('reserved_participation', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisations',
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('tree', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('organisation_id')
    )
    op.create_table('company_cpv_codes',
    sa.Column('company_vat_number', sa.String(), nullable=True),
    sa.Column('cpv_code_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_vat_number'], ['companies.vat_number'], ),
    sa.ForeignKeyConstraint(['cpv_code_code'], ['cpv_codes.code'], )
    )
    op.create_table('descriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('dossier_reference_number', sa.String(), nullable=True),
    sa.Column('cpv_code_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cpv_code_code'], ['cpv_codes.code'], ),
    sa.ForeignKeyConstraint(['dossier_reference_number'], ['dossiers.reference_number'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enterprise_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_code', sa.String(), nullable=False),
    sa.Column('levels', sa.PickleType(), nullable=False),
    sa.Column('dossier_reference_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_reference_number'], ['dossiers.reference_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisation_names',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ),
    sa.PrimaryKeyConstraint('text')
    )
    op.create_table('publications',
    sa.Column('publication_workspace_id', sa.String(), nullable=False),
    sa.Column('dispatch_date', sa.DateTime(), nullable=False),
    sa.Column('insertion_date', sa.DateTime(), nullable=False),
    sa.Column('natures', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('notice_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('notice_sub_type', sa.String(), nullable=False),
    sa.Column('nuts_codes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('procedure_id', sa.String(), nullable=False),
    sa.Column('publication_date', sa.DateTime(), nullable=False),
    sa.Column('publication_languages', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('publication_reference_numbers_bda', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('publication_reference_numbers_ted', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('publication_type', sa.String(), nullable=False),
    sa.Column('published_at', sa.ARRAY(sa.DateTime()), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('sent_at', sa.ARRAY(sa.DateTime()), nullable=False),
    sa.Column('ted_published', sa.Boolean(), nullable=False),
    sa.Column('vault_submission_deadline', sa.DateTime(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('cpv_main_code_code', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('dossier_reference_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cpv_main_code_code'], ['cpv_codes.code'], ),
    sa.ForeignKeyConstraint(['dossier_reference_number'], ['dossiers.reference_number'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ),
    sa.PrimaryKeyConstraint('publication_workspace_id')
    )
    op.create_table('publication_cpv_additional_codes',
    sa.Column('publication_publication_workspace_id', sa.String(), nullable=True),
    sa.Column('cpv_code_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cpv_code_code'], ['cpv_codes.code'], ),
    sa.ForeignKeyConstraint(['publication_publication_workspace_id'], ['publications.publication_workspace_id'], )
    )
    op.create_table('publication_lots',
    sa.Column('publication_publication_workspace_id', sa.String(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['publication_publication_workspace_id'], ['publications.publication_workspace_id'], )
    )
    op.create_table('publications_companies',
    sa.Column('publication_publication_workspace_id', sa.String(), nullable=True),
    sa.Column('company_vat_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_vat_number'], ['companies.vat_number'], ),
    sa.ForeignKeyConstraint(['publication_publication_workspace_id'], ['publications.publication_workspace_id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publications_companies')
    op.drop_table('publication_lots')
    op.drop_table('publication_cpv_additional_codes')
    op.drop_table('publications')
    op.drop_table('organisation_names')
    op.drop_table('enterprise_categories')
    op.drop_table('descriptions')
    op.drop_table('company_cpv_codes')
    op.drop_table('organisations')
    op.drop_table('lots')
    op.drop_table('dossiers')
    op.drop_table('cpv_codes')
    op.drop_table('companies')
    # ### end Alembic commands ###
