CPV_CODES = {
    "Andere diensten": {
        "92000000": "Cultuur-, sport- en recreatiediensten",
        "55000000": "Diensten voor hotel, restaurant en detailhandel",
        "75000000": "Diensten voor openbaar bestuur, defensie en sociale verzekering",
        "85000000": "Gezondheidszorg en maatschappelijk werk",
        "51000000": "Installatiediensten (uitgezonderd software)",
        "63000000": "Ondersteunende en aanvullende vervoersdiensten; reisbureaudiensten",
        "65000000": "Openbare voorzieningen",
        "98000000": "Overige gemeenschaps-, sociale en persoonlijke diensten",
        "64000000": "Post- en telecommunicatiediensten",
        "50000000": "Reparatie- en onderhoudsdiensten",
    },
    "Bouw en onroerend goed": {
        "45000000": "Bouwwerkzaamheden",
        "45400000": "Afwerking van gebouwen",
        "45100000": "Bouwrijp maken van terreinen",
        "45300000": "Installatiewerkzaamheden in de bouw",
        "45500000": "Verhuur van bouw- en civieltechnische installaties en uitrusting met bedieningspersoneel",
        "45200000": "Volledige of gedeeltelijke bouw- en civieltechnische werkzaamheden",
        "90000000": "Diensten inzake afvalwater, afval, reiniging en milieu",
        "90400000": "Diensten in verband met afvalwater",
        "90500000": "Diensten op het gebied van vuilnis en afval",
        "90700000": "Milieuzorgdiensten",
        "90900000": "Schoonmaak- en afvalverwijderingsdiensten",
        "90600000": "Verwijderen, schoonmaken en ontsmetten binnen een stedelijke en/of landelijke omgeving",
        "71000000": "Dienstverlening op het gebied van architectuur, bouwkunde, civiele techniek en inspectie",
        "71800000": "Adviesdiensten voor watervoorziening en afval",
        "71500000": "Diensten in verband met de bouw",
        "71600000": "Diensten voor technische testen, analyse en adviezen",
        "71300000": "Dienstverlening door ingenieurs",
        "71200000": "Dienstverlening op het gebied van architectuur en dergelijke",
        "71400000": "Dienstverlening op het gebied van stedenbouw en landschapsarchitectuur",
        "71900000": "Laboratoriumdiensten",
        "71700000": "Meet- en controlediensten",
        "70000000": "Makelaarsdiensten",
        "70300000": "Makelaarsdiensten op honorarium- of contractbasis",
        "70100000": "Makelaarsdiensten voor onroerend goed in eigen beheer",
        "70200000": "Verhuur of leasing van eigen onroerend goed",
    },
    "Computer- en aanverwante diensten": {
        "72000000": "IT-diensten: adviezen, softwareontwikkeling, internet en ondersteuning",
        "72100000": "Advies inzake hardware",
        "72800000": "Computeraudit- en testdiensten",
        "72700000": "Computernetwerkdiensten",
        "72900000": "Diensten voor computerbackup en converteren van computercatalogus",
        "72600000": "Diensten voor computerondersteuning en -advies",
        "72500000": "Informaticadiensten",
        "72400000": "Internetdiensten",
        "72200000": "Softwareprogrammering en -advies",
        "72300000": "Uitwerken van gegevens",
        "30000000": "Kantoormachines en gegevensverwerkende apparatuur, kantooruitrusting en -benodigdheden, uitgez. meubilair en softwarepakketten",
        "30200000": "Computeruitrusting en -benodigdheden",
        "30100000": "Kantoormachines, -uitrusting en -benodigdheden, uitgez. computers, printers en meubilair",
        "48000000": "Software en informatiesystemen",
        "48500000": "Communicatie- en multimediasoftware",
        "48600000": "Database- en besturingssoftware",
        "48900000": "Diverse software en computersystemen",
        "48800000": "Informatiesystemen en servers",
        "48300000": "Software voor het maken van documenten, tekeningen, afbeeldingen, dienstregelingen en productiviteit",
        "48200000": "Software voor netwerken, internet en intranet",
        "48400000": "Software voor zakelijke transacties en persoonlijke zaken",
        "48700000": "Softwarevoorzieningen",
        "48100000": "Speciale software voor de industrie",
    },
    "Defensie en veiligheid": {
        "45222200": "Civiele techniek voor militaire installaties",
        "45222300": "Civiele techniek voor veiligheidsinstallaties",
        "45111310": "Demontagewerkzaamheden voor militaire installaties",
        "45111320": "Demontagewerkzaamheden voor veiligheidsinstallaties",
        "75000000": "Diensten voor openbaar bestuur, defensie en sociale verzekering",
        "45216000": "Gebouwen voor rechts- of ordehandhaving of noodhulpdiensten, en militaire gebouwen",
        "51550000": "Installatie van wapensystemen",
        "31642200": "Mijndetectieapparatuur",
        "73400000": "O&O-diensten voor beveiligings- en defensiematerialen",
        "72231000": "Ontwikkeling van software voor militaire doeleinden",
        "80600000": "Opleidingsdiensten voor defensie- en veiligheidsmaterieel",
        "50600000": "Reparatie- en onderhoudsdiensten voor beveiligings- en defensiematerialen",
        "35000000": "Uitrusting voor veiligheid, brandweer, politie en leger",
    },
    "Drukken en uitgeven": {
        "22000000": "Drukwerk en aanverwante producten",
        "30000000": "Kantoormachines en gegevensverwerkende apparatuur, kantooruitrusting en -benodigdheden, uitgez. meubilair en softwarepakketten",
        "30200000": "Computeruitrusting en -benodigdheden",
        "30100000": "Kantoormachines, -uitrusting en -benodigdheden, uitgez. computers, printers en meubilair",
        "79000000": "Zakelijke dienstverlening: juridisch, marketing, consulting, drukkerij en beveiliging",
    },
    "Energie- en aanverwante diensten": {
        "09000000": "Aardolieproducten, brandstof, elektriciteit en andere energiebronnen",
        "76000000": "Diensten in verband met de olie- en gasindustrie",
    },
    "Financiële en aanverwante diensten": {
        "66000000": "Financiële en verzekeringsdiensten",
        "66100000": "Diensten op het gebied van banken en investeringen",
        "66500000": "Diensten op het gebied van verzekeringen en pensioenen",
        "66700000": "Herverzekeringen",
        "66600000": "Kasdiensten",
    },
    "Landbouw en voeding": {
        "77000000": "Diensten voor land-, bos- en tuinbouw, aquicultuur en imkerij",
        "03000000": "Landbouw- en veeteelt-, kwekerij-, visserij-, bosbouw- en aanverwante producten",
        "15000000": "Voeding, dranken, tabak en aanverwante producten",
    },
    "Materialen en producten": {
        "09000000": "Aardolieproducten, brandstof, elektriciteit en andere energiebronnen",
        "24000000": "Chemische producten",
        "22000000": "Drukwerk en aanverwante producten",
        "31000000": "Elektrische machines, apparaten, uitrusting en verbruiksartikelen; verlichting",
        "30000000": "Kantoormachines en gegevensverwerkende apparatuur, kantooruitrusting en -benodigdheden, uitgez. meubilair en softwarepakketten",
        "30200000": "Computeruitrusting en -benodigdheden",
        "30100000": "Kantoormachines, -uitrusting en -benodigdheden, uitgez. computers, printers en meubilair",
        "18000000": "Kleding, schoeisel, bagageartikelen en accessoires",
        "03000000": "Landbouw- en veeteelt-, kwekerij-, visserij-, bosbouw- en aanverwante producten",
        "19000000": "Leder, textielweefsels, kunststof en rubber materialen",
        "33000000": "Medische apparatuur, farmaceutische artikelen en artikelen voor lichaamsverzorging",
        "39000000": "Meubelen (m.i.v. kantoormeubelen), inrichtingsartikelen, huishoudelijke apparaten (uitgez. verlichting) en schoonmaakproducten",
        "14000000": "Mijnbouw, basismetalen en aanverwante producten",
        "37000000": "Muziekinstrumenten, sportartikelen, spelletjes, speelgoed, handwerk, kunstartikelen en toebehoren",
        "32000000": "Radio-, televisie-, communicatie-, telecommunicatietoestellen en aanverwante apparatuur",
        "44000000": "Structuren en materialen voor de bouw; ondersteunende producten voor de bouw (uitgezonderd elektrische apparatuur)",
        "35000000": "Uitrusting voor veiligheid, brandweer, politie en leger",
        "34000000": "Vervoersmaterieel en bijbehorende producten",
        "15000000": "Voeding, dranken, tabak en aanverwante producten",
    },
    "Mijnbouw en ersten": {
        "14000000": "Mijnbouw, basismetalen en aanverwante producten",
        "44000000": "Structuren en materialen voor de bouw; ondersteunende producten voor de bouw (uitgezonderd elektrische apparatuur)",
    },
    "Milieu en afvalverwerking": {
        "90000000": "Diensten inzake afvalwater, afval, reiniging en milieu",
        "90400000": "Diensten in verband met afvalwater",
        "90500000": "Diensten op het gebied van vuilnis en afval",
        "90700000": "Milieuzorgdiensten",
        "90900000": "Schoonmaak- en afvalverwijderingsdiensten",
        "90600000": "Verwijderen, schoonmaken en ontsmetten binnen een stedelijke en/of landelijke omgeving",
        "41000000": "Verzameld en gezuiverd water",
    },
    "Onderwijs": {
        "80000000": "Diensten voor onderwijs en opleiding",
    },
    "Onderzoek en ontwikkeling": {
        "73000000": "Onderzoek en ontwikkeling, en aanverwante adviezen",
    },
    "Technologie en uitrusting": {
        "42000000": "Bedrijfsmachines",
        "31000000": "Elektrische machines, apparaten, uitrusting en verbruiksartikelen; verlichting",
        "30000000": "Kantoormachines en gegevensverwerkende apparatuur, kantooruitrusting en -benodigdheden, uitgez. meubilair en softwarepakketten",
        "30200000": "Computeruitrusting en -benodigdheden",
        "30100000": "Kantoormachines, -uitrusting en -benodigdheden, uitgez. computers, printers en meubilair",
        "38000000": "Laboratoriuminstrumenten, optische en precisie-instrumenten (uitgezonderd brillen)",
        "16000000": "Landbouwmachines",
        "43000000": "Machines voor de mijnbouw, steengroeven en voor de bouw",
        "33000000": "Medische apparatuur, farmaceutische artikelen en artikelen voor lichaamsverzorging",
        "39000000": "Meubelen (m.i.v. kantoormeubelen), inrichtingsartikelen, huishoudelijke apparaten (uitgez. verlichting) en schoonmaakproducten",
        "32000000": "Radio-, televisie-, communicatie-, telecommunicatietoestellen en aanverwante apparatuur",
        "48000000": "Software en informatiesystemen",
        "48500000": "Communicatie- en multimediasoftware",
        "48600000": "Database- en besturingssoftware",
        "48900000": "Diverse software en computersystemen",
        "48800000": "Informatiesystemen en servers",
        "48300000": "Software voor het maken van documenten, tekeningen, afbeeldingen, dienstregelingen en productiviteit",
        "48200000": "Software voor netwerken, internet en intranet",
        "48400000": "Software voor zakelijke transacties en persoonlijke zaken",
        "48700000": "Softwarevoorzieningen",
        "48100000": "Speciale software voor de industrie",
        "35000000": "Uitrusting voor veiligheid, brandweer, politie en leger",
        "34000000": "Vervoersmaterieel en bijbehorende producten",
    },
    "Vervoers- en aanverwante diensten": {
        "63000000": "Ondersteunende en aanvullende vervoersdiensten; reisbureaudiensten",
        "60000000": "Vervoersdiensten (uitg. vervoer van afval)",
        "34000000": "Vervoersmaterieel en bijbehorende producten",
    },
}

def get_cpv_sector_and_description(input_cpv: str, cpv_codes: dict) -> tuple[bool, str, str]:
    # Extract the main part of the CPV code before the hyphen
    cpv_main = input_cpv.split('-')[0]  # e.g., "45232440-8" -> "45232440"
    
    # Extract first three and first two digits
    first_two = cpv_main[:2] + "000000"
    first_three = cpv_main[:3] + "00000"
    first_six = cpv_main[:6] + "00"
    full_code = cpv_main[:8]  # The full CPV code without the checksum
    
    # Check if any of these exist in the provided CPV dictionary keys
    for sector, codes in cpv_codes.items():
        for code in [first_two, first_three, first_six, full_code]:
            if code in codes:
                return True, sector, codes[code]
    
    return False, "Unknown", "Unknown"
